# Generated by Django 4.1.2 on 2022-11-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteUser',
        ),
    ]
