# Generated by Django 4.1.2 on 2022-11-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_info_sumrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='sumRev',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
