# Generated by Django 4.1.2 on 2023-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_info_sumrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='web',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='website page'),
        ),
    ]
